### ISSUE TITLE
Routes

### ISSUE THREAD

**Issue by ajansel** [Yihwan/faquity#4]
# Routes

- [x] Routes accurately reflect MVPs and Component Hierarchy
  - You will need an API endpoint for search (potential you asset index route)
  - For "updating" your watchlists do you mean `unwatching` basically? If so, that would be better off as a `delete` request
  - Your `get` request for assets should be `id` not `symbol`
  - One thing I'd like to clarify is the buying / selling process. Will that be another fill? 
  - We can clarify these routes in our discussion tomorrow
- [x] Covers the frontend functionality of the site through routes that match to the wireframes
  - How will you do searching? A search bar? Or will it need its own route?
- [x] Contains the following sections: HTML, API Endpoints(Backend), and Frontend Routes
  - Make sure to add your static pages route under an HTML section and you should be in good shape 
- [x] Each route has a description
- [x] API Endpoint routes contains wildcard variables written in `snake_case`
  - These need updated because on the backend we will expect them to be snake_case in our params
- [x] Frontend routes contains wildcard variables written in `camelCase`
- [x] Have API routes that will allow the front end to get all info it needs and does not have unneeded routes:
    + probably doesn't need a `GET likes` api endpoint bc that info comes through the post show
- [x] Correctly formatted
    - [x] Routes are displayed with `inline coding text` (backticks)

# Comments:
- Hmm, what do you mean for the security concerns? We could discuss this tomorrow in person. 
- Great job!

**Comment by Yihwan** [comment]
fixed api endpoints to be in snake_case

**Comment by Yihwan** [comment]
added html static routes

**Comment by Yihwan** [comment]
added delete/post routes to watchlists for watching/unwatching asset, changed asset get request for ids to reference :id, not :symbol

**Comment by ajansel** [comment]
Good to go, good work!
